///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WidthAndDistance
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WidthAndDistanceRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("49f38350-1ab7-4474-8c91-fe3695110c9e")]
    public partial class WidthAndDistanceRepository : RepoGenBaseFolder
    {
        static WidthAndDistanceRepository instance = new WidthAndDistanceRepository();
        WidthAndDistanceRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;

        /// <summary>
        /// Gets the singleton class instance representing the WidthAndDistanceRepository element repository.
        /// </summary>
        [RepositoryFolder("49f38350-1ab7-4474-8c91-fe3695110c9e")]
        public static WidthAndDistanceRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WidthAndDistanceRepository() 
            : base("WidthAndDistanceRepository", "/", null, 0, false, "49f38350-1ab7-4474-8c91-fe3695110c9e", ".\\RepositoryImages\\WidthAndDistanceRepository49f38350.rximgres")
        {
            _snapxuntitled = new WidthAndDistanceRepositoryFolders.SnapXUntitledAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("49f38350-1ab7-4474-8c91-fe3695110c9e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("794af6d0-d648-4b96-a8d8-a3abc7f22709")]
        public virtual WidthAndDistanceRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class WidthAndDistanceRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("794af6d0-d648-4b96-a8d8-a3abc7f22709")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _finishInfo;
            //RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "794af6d0-d648-4b96-a8d8-a3abc7f22709", "")
            {
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "element[@controlid='94']", 600000, null, "df190dde-cc44-40fe-b254-75b746fe4644");
                _finishInfo = new RepoItemInfo(this, "Finish", "container[@controlid='59648']/form//button[@text='Finish' and @enabled='True']", 600000, null, "2929854b-a65c-454d-9786-d7e3a4c5a3f7");
                //_buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container[@controlid='59648']/form//button[@text='&OK']", 600000, null, "3b5b15d3-1337-46bc-9a08-9ae085b9db9d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("794af6d0-d648-4b96-a8d8-a3abc7f22709")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("794af6d0-d648-4b96-a8d8-a3abc7f22709")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("df190dde-cc44-40fe-b254-75b746fe4644")]
            public virtual Ranorex.Unknown TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("df190dde-cc44-40fe-b254-75b746fe4644")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The Finish item.
            /// </summary>
            [RepositoryItem("2929854b-a65c-454d-9786-d7e3a4c5a3f7")]
            public virtual Ranorex.Button Finish
            {
                get
                {
                    return _finishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Finish item info.
            /// </summary>
            [RepositoryItemInfo("2929854b-a65c-454d-9786-d7e3a4c5a3f7")]
            public virtual RepoItemInfo FinishInfo
            {
                get
                {
                    return _finishInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            //[RepositoryItem("3b5b15d3-1337-46bc-9a08-9ae085b9db9d")]
            //public virtual Ranorex.Button ButtonOK
            //{
            //    get
            //    {
            //        return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
            //    }
            //}

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            //[RepositoryItemInfo("3b5b15d3-1337-46bc-9a08-9ae085b9db9d")]
            //public virtual RepoItemInfo ButtonOKInfo
            //{
            //    get
            //    {
            //        return _buttonokInfo;
            //    }
            //}
        }

    }
#pragma warning restore 0436
}